name:                default-map
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/marcosh/default-map#readme
license:             OtherLicense
author:              Marco Perone
maintainer:          pasafama@gmail.com
copyright:           2021 Marco Perone
category:            Library
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  -W
  -Wall
  -Werror
  -fwrite-ide-info
  -hiedir=.hie

library:
  source-dirs:      src
  dependencies:
    - containers
    - hashable
    - unordered-containers

tests:
  default-map-spec:
    main:           Spec.hs
    source-dirs:    test
    dependencies:
      - default-map
      - hspec
      - QuickCheck
